import type {
  AdminCandidateProfileDetailDto,
  AdminCandidateProfileDetailResponseDto,
  AdminCandidateProfileDeviceTokenExportDto,
  AdminCandidateProfileErasureResponseDto,
  AdminCandidateProfileEventParticipationExportDto,
  AdminCandidateProfileExportResponseDto,
  AdminCandidateProfileIdentityAccessReviewExportDto,
  AdminCandidateProfileListResponseDto,
  AdminCandidateProfileMembershipExportDto,
  AdminCandidateProfileBrotherConversionResponseDto,
  AdminCandidateProfileBrotherMembershipDto,
  AdminCandidateProfileOfficerAssignmentExportDto,
  AdminCandidateProfileProviderAccountExportDto,
  AdminCandidateProfileRoadmapAssignmentExportDto,
  AdminCandidateProfileSummaryDto,
  AdminCandidateProfileUserRoleExportDto,
  ConvertCandidateProfileToBrotherDto,
  UpdateAdminCandidateProfileDto
} from "@jp2/shared-validation";

export type AdminCandidateProfileSummary = AdminCandidateProfileSummaryDto;
export type AdminCandidateProfileDetail = AdminCandidateProfileDetailDto;
export type AdminCandidateProfileProviderAccountExport =
  AdminCandidateProfileProviderAccountExportDto;
export type AdminCandidateProfileDeviceTokenExport = AdminCandidateProfileDeviceTokenExportDto;
export type AdminCandidateProfileUserRoleExport = AdminCandidateProfileUserRoleExportDto;
export type AdminCandidateProfileIdentityAccessReviewExport =
  AdminCandidateProfileIdentityAccessReviewExportDto;
export type AdminCandidateProfileMembershipExport = AdminCandidateProfileMembershipExportDto;
export type AdminCandidateProfileBrotherMembership = AdminCandidateProfileBrotherMembershipDto;
export type AdminCandidateProfileOfficerAssignmentExport =
  AdminCandidateProfileOfficerAssignmentExportDto;
export type AdminCandidateProfileRoadmapAssignmentExport =
  AdminCandidateProfileRoadmapAssignmentExportDto;
export type AdminCandidateProfileEventParticipationExport =
  AdminCandidateProfileEventParticipationExportDto;
export type AdminCandidateProfileListResponse = AdminCandidateProfileListResponseDto;
export type AdminCandidateProfileDetailResponse = AdminCandidateProfileDetailResponseDto;
export type AdminCandidateProfileExportResponse = AdminCandidateProfileExportResponseDto;
export type AdminCandidateProfileErasureResponse = AdminCandidateProfileErasureResponseDto;
export type AdminCandidateProfileBrotherConversionResponse =
  AdminCandidateProfileBrotherConversionResponseDto;
export type UpdateAdminCandidateProfile = UpdateAdminCandidateProfileDto;
export type ConvertCandidateProfileToBrother = ConvertCandidateProfileToBrotherDto;
