export const ADMIN_AUDIT_ACTIONS = [
  "admin.candidateRequest.export",
  "admin.candidateRequest.erase",
  "admin.candidateRequest.update",
  "admin.candidateRequest.convert",
  "admin.candidateProfile.export",
  "admin.candidateProfile.erase",
  "admin.candidateProfile.update",
  "admin.roadmapSubmission.export",
  "admin.roadmapSubmission.erase",
  "admin.roadmapSubmission.approved",
  "admin.roadmapSubmission.rejected",
  "admin.roadmapAssignment.create",
  "admin.identityAccess.confirm",
  "admin.identityAccess.reject",
  "admin.organizationUnit.create",
  "admin.organizationUnit.update",
  "admin.prayer.create",
  "admin.prayer.approve",
  "admin.prayer.publish",
  "admin.prayer.archive",
  "admin.prayer.update",
  "admin.event.create",
  "admin.event.approve",
  "admin.event.publish",
  "admin.event.cancel",
  "admin.event.archive",
  "admin.event.update",
  "admin.announcement.create",
  "admin.announcement.approve",
  "admin.announcement.publish",
  "admin.announcement.push_dispatch",
  "admin.announcement.archive",
  "admin.announcement.update",
  "admin.silent_prayer_event.create",
  "admin.silent_prayer_event.approve",
  "admin.silent_prayer_event.publish",
  "admin.silent_prayer_event.archive",
  "admin.silent_prayer_event.update"
] as const;

export type AdminAuditAction = (typeof ADMIN_AUDIT_ACTIONS)[number];
